# Generated by Django 5.0.2 on 2024-02-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
    ]
